/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tigron' at '26/05/16 15:58' with Gradle 2.9
 *
 * @author Tigron, @date 26/05/16 15:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
